### ISSUE TITLE
Excessive graphic memory usage in inference phace

### ISSUE THREAD

**Issue by pd162** [ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection#8]
Thanks for your contribution! However, some exceptions occured when I reproduce the results in your paper.

I tried to use your checkpoint to inference Art test set. The following are the script and the error log.

`python demo/art_demo.py --checkpoint pretrained_model/checkpoint
s/res50_regioncl_finetuned_epoch_8.pth --config configs/i3cl_r50_regioncl_fpn/i3cl_r50_fpn_ms_finetune.py --score-thr 0.45 --json_file output/r50_art.json
`

> Traceback (most recent call last):
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/art_demo.py", line 128, in <module>
    main(args)
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/art_demo.py", line 65, in main
    result = inference_detector(model, img_path)
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/../mmdet/apis/inference.py", line 147, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/data1/ljh/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/ljh/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/../mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/../mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/../mmdet/models/detectors/two_stage.py", line 214, in simple_test
    return self.roi_head.simple_test(
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/../mmdet/models/roi_heads/standard_roi_head.py", line 284, in simple_test
    segm_results = self.simple_test_mask(
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/../mmdet/models/roi_heads/test_mixins.py", line 274, in simple_test_mask
    segm_result = self.mask_head.get_seg_masks(
  File "/data1/ljh/code/ViTAE-Transformer-Scene-Text-Detection/demo/../mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 277, in get_seg_masks
    assert (num_chunks <=
AssertionError: Default GPU_MEM_LIMIT is too small; try increasing it

When I increased the GPU_MEM_LIMIT, CUDA out of memory exception occured.

In addition, during the inference phase, the graphic memory increases until CUDA out of memory. After reducing img_sizes of the test images, Above errors still exist.

Could you give me a solution? Thank you!

**Comment by ymy-k** [comment]
I didn't have this issue before. How much is your GPU memory?

**Comment by pd162** [comment]
> I didn't have this issue before. How much is your GPU memory?

RTX 2080Ti, 11GB
